name: flatland-baselines
dependencies:
  - python==3.12.9
  - pip:
      - pytest
      # DEPENDENCY SWITCH:
      - git+https://github.com/flatland-association/flatland-rl.git@178-agents-living-on-the-edge-14
      #- flatland-rl[ml]==4.3.0