name: flatland-baselines
dependencies:
  - python==3.12.9
  - pip:
      - pytest
      # DEPENDENCY SWITCH:
      # - git+https://github.com/flatland-association/flatland-rl.git@main
      - flatland-rl[ml]==4.2.3
